completed css-grid-classes | Janelle Gatmaitan
JanelleGatmaitan/c0121-code-solutions pull request #16
Opened 2021-01-21 21:28 UTC by JanelleGatmaitan

![image](https://user-images.githubusercontent.com/68579034/105414633-9844fe80-5bec-11eb-9bed-586e38044cf4.png)

2021-01-21 23:02 UTC, codingcodymiller requested changes
Hey Janelle, great code so far! Please see my notes

2021-01-21 23:02 UTC, codingcodymiller commented on css-grid-classes/styles.css
> +}
These should be removed. Just reuse the `column-one-third` class.

2021-01-21 23:02 UTC, codingcodymiller commented on css-grid-classes/styles.css
> +}
These should be removed.

2021-01-21 23:02 UTC, codingcodymiller commented on css-grid-classes/styles.css
> +}
These should be removed.

2021-01-21 23:16 UTC, JanelleGatmaitan commented
![image](https://user-images.githubusercontent.com/68579034/105424137-abab9600-5bfb-11eb-8d9d-b6f82fa00262.png)

2021-01-22 20:49 UTC, codingcodymiller approved these changes
Nicely done!! 👍

2021-01-22 23:28 UTC, merged