Css canvas medical | Janelle Gatmaitan
JanelleGatmaitan/c0121-code-solutions pull request #32
Opened 2021-01-29 08:03 UTC by JanelleGatmaitan

![image](https://user-images.githubusercontent.com/68579034/106248114-62dc7a00-61c5-11eb-9458-517e7711cae2.png)

2021-01-29 18:43 UTC, thebearingedge requested changes
Looking pretty good. Please include more screenshots so we can review the whole page. Also, here are some tips for cleaning up the code.

2021-01-29 18:43 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +  font-family: 'Avenir';
Your font families are showing up in multiple classes. See if you can remove some duplication with group selectors

```css
body,
button {
  font-family: ...
}
```

2021-01-29 18:43 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +  border-radius: 3px;
You could probably apply some of these styles to _all_ buttons

```css
button {
  ...
}
```

2021-01-29 18:43 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +  top: 40px;
Rather than reach for positioning, try leveraging the box model of the parent element instead (padding).

2021-01-29 18:43 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +}
Be sure to stay consistent with your casing. `camelCase` is fine, but we generally stick with `kebab-case` at LearningFuze.

2021-01-29 18:43 UTC, thebearingedge commented on css-canvas-medical/index.html
> +            <li class="firstLi"><a href="">Company</a></li>
Try a heading element for each of these lists instead of styling the first list item.

2021-02-16 05:41 UTC, JanelleGatmaitan commented
![image](https://user-images.githubusercontent.com/68579034/108022993-83367200-6fd6-11eb-966b-c9e19678e90a.png)
![image](https://user-images.githubusercontent.com/68579034/108023018-8df10700-6fd6-11eb-99c5-97136ba1fa7f.png)

2021-02-17 18:27 UTC, codingcodymiller approved these changes
🥳 🥳 🥳

2021-02-18 05:59 UTC, merged