completed array-manipulation-1 | Janelle Gatmaitan
JanelleGatmaitan/c0121-code-solutions pull request #35
Opened 2021-02-01 03:51 UTC by JanelleGatmaitan

![image](https://user-images.githubusercontent.com/68579034/106412944-b5a07680-63fd-11eb-9691-cad3da3184ec.png)
![image](https://user-images.githubusercontent.com/68579034/106412959-bfc27500-63fd-11eb-811d-8ee15449ea38.png)

2021-02-01 17:21 UTC, thebearingedge requested changes

2021-02-01 17:21 UTC, thebearingedge commented on array-manipulation-1/src/reverse.js
> +debugger;
Please remove all `debugger` statements before turning in your solution.

2021-02-01 17:21 UTC, thebearingedge commented on array-manipulation-1/src/reverse.js
> +reverse([1, 2, 3]);
Please remove your test code before turning in your solution.

2021-02-01 17:21 UTC, thebearingedge commented on array-manipulation-1/src/compact.js
> +debugger;
Please remove all `debugger` statements before turning in your solution.

2021-02-01 17:21 UTC, thebearingedge commented on array-manipulation-1/src/compact.js
> +compact([[], [], []]);
Please remove your test code before turning in your solution.

2021-02-02 19:04 UTC, codingcodymiller approved these changes

2021-02-02 20:31 UTC, merged