completed javascript-modal | Janelle Gatmaitan
JanelleGatmaitan/c0121-code-solutions pull request #42
Opened 2021-02-03 01:30 UTC by JanelleGatmaitan

![image](https://user-images.githubusercontent.com/68579034/106684967-5157f100-657c-11eb-8c87-c0f2b55cc57b.png)
![image](https://user-images.githubusercontent.com/68579034/106685000-5f0d7680-657c-11eb-97e9-30b7e0405e6a.png)

2021-02-03 02:13 UTC, codingcodymiller requested changes
Nice work so far! Please see my note

2021-02-03 02:13 UTC, codingcodymiller commented on javascript-modal/main.js
> +  if (click === true) {
It doesn't look like this variable is ever changing in value. You can just delete the variable, and the conditionals referencing it.

2021-02-03 14:56 UTC, thebearingedge requested changes

2021-02-03 14:56 UTC, thebearingedge commented on javascript-modal/main.js
> +  }
You can remove the `if` statement altogether, since `true` is always `true`.

2021-02-03 14:56 UTC, thebearingedge commented on javascript-modal/main.js
> +  }
You can remove the `if` statement altogether, since `true` is always `true`.

2021-02-06 21:15 UTC, thebearingedge approved these changes

2021-02-06 23:44 UTC, merged