completed css-four-column-layout | Janelle Gatmaitan
JanelleGatmaitan/c0121-code-solutions pull request #61
Opened 2021-03-01 01:21 UTC by JanelleGatmaitan

![image](https://user-images.githubusercontent.com/68579034/109441163-5a0bdd80-79e9-11eb-9a72-b0f4b39dd4c9.png)

2021-03-01 16:51 UTC, thebearingedge requested changes

2021-03-01 16:51 UTC, thebearingedge commented on css-four-column-layout/index.html
> +  </div>
Try organizing everything into four columns that each include the phone image, icon, and feature.

2021-03-10 04:59 UTC, JanelleGatmaitan commented
organized columns to include phone img, icon, feature
![image](https://user-images.githubusercontent.com/68579034/110578745-4d3e6680-811a-11eb-8ddd-6f47e76ddb68.png)

2021-03-10 18:09 UTC, thebearingedge approved these changes

2021-03-10 18:42 UTC, merged